//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type EntitySchemasParametersMappings struct {
	ID            int64 `sql:"primary_key"`
	TenantID      uuid.UUID
	SchemaKey     string
	SchemaVersion string
	ParameterKey  string
	IsRequired    *bool
	CreatedAt     *time.Time
	UpdatedAt     *time.Time
}
