//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type EntitySchemas struct {
	ID            int64 `sql:"primary_key"`
	TenantID      uuid.UUID
	SchemaKey     string
	SchemaName    string
	SchemaVersion string
	Description   *string
	IsLatest      *bool
	Lifecycle     *string
	CreatedAt     *time.Time
	UpdatedAt     *time.Time
}
