//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var EntitySchemasParametersMappings = newEntitySchemasParametersMappingsTable("public", "entity_schemas_parameters_mappings", "")

type entitySchemasParametersMappingsTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnInteger
	TenantID      postgres.ColumnString
	SchemaKey     postgres.ColumnString
	SchemaVersion postgres.ColumnString
	ParameterKey  postgres.ColumnString
	IsRequired    postgres.ColumnBool
	CreatedAt     postgres.ColumnTimestampz
	UpdatedAt     postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type EntitySchemasParametersMappingsTable struct {
	entitySchemasParametersMappingsTable

	EXCLUDED entitySchemasParametersMappingsTable
}

// AS creates new EntitySchemasParametersMappingsTable with assigned alias
func (a EntitySchemasParametersMappingsTable) AS(alias string) *EntitySchemasParametersMappingsTable {
	return newEntitySchemasParametersMappingsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EntitySchemasParametersMappingsTable with assigned schema name
func (a EntitySchemasParametersMappingsTable) FromSchema(schemaName string) *EntitySchemasParametersMappingsTable {
	return newEntitySchemasParametersMappingsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EntitySchemasParametersMappingsTable with assigned table prefix
func (a EntitySchemasParametersMappingsTable) WithPrefix(prefix string) *EntitySchemasParametersMappingsTable {
	return newEntitySchemasParametersMappingsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EntitySchemasParametersMappingsTable with assigned table suffix
func (a EntitySchemasParametersMappingsTable) WithSuffix(suffix string) *EntitySchemasParametersMappingsTable {
	return newEntitySchemasParametersMappingsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEntitySchemasParametersMappingsTable(schemaName, tableName, alias string) *EntitySchemasParametersMappingsTable {
	return &EntitySchemasParametersMappingsTable{
		entitySchemasParametersMappingsTable: newEntitySchemasParametersMappingsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                             newEntitySchemasParametersMappingsTableImpl("", "excluded", ""),
	}
}

func newEntitySchemasParametersMappingsTableImpl(schemaName, tableName, alias string) entitySchemasParametersMappingsTable {
	var (
		IDColumn            = postgres.IntegerColumn("id")
		TenantIDColumn      = postgres.StringColumn("tenant_id")
		SchemaKeyColumn     = postgres.StringColumn("schema_key")
		SchemaVersionColumn = postgres.StringColumn("schema_version")
		ParameterKeyColumn  = postgres.StringColumn("parameter_key")
		IsRequiredColumn    = postgres.BoolColumn("is_required")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampzColumn("updated_at")
		allColumns          = postgres.ColumnList{IDColumn, TenantIDColumn, SchemaKeyColumn, SchemaVersionColumn, ParameterKeyColumn, IsRequiredColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{TenantIDColumn, SchemaKeyColumn, SchemaVersionColumn, ParameterKeyColumn, IsRequiredColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = postgres.ColumnList{IDColumn, IsRequiredColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return entitySchemasParametersMappingsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		TenantID:      TenantIDColumn,
		SchemaKey:     SchemaKeyColumn,
		SchemaVersion: SchemaVersionColumn,
		ParameterKey:  ParameterKeyColumn,
		IsRequired:    IsRequiredColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
