//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var EntitySchemas = newEntitySchemasTable("public", "entity_schemas", "")

type entitySchemasTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnInteger
	TenantID      postgres.ColumnString
	SchemaKey     postgres.ColumnString
	SchemaName_   postgres.ColumnString
	SchemaVersion postgres.ColumnString
	Description   postgres.ColumnString
	IsLatest      postgres.ColumnBool
	Lifecycle     postgres.ColumnString
	CreatedAt     postgres.ColumnTimestampz
	UpdatedAt     postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type EntitySchemasTable struct {
	entitySchemasTable

	EXCLUDED entitySchemasTable
}

// AS creates new EntitySchemasTable with assigned alias
func (a EntitySchemasTable) AS(alias string) *EntitySchemasTable {
	return newEntitySchemasTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EntitySchemasTable with assigned schema name
func (a EntitySchemasTable) FromSchema(schemaName string) *EntitySchemasTable {
	return newEntitySchemasTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EntitySchemasTable with assigned table prefix
func (a EntitySchemasTable) WithPrefix(prefix string) *EntitySchemasTable {
	return newEntitySchemasTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EntitySchemasTable with assigned table suffix
func (a EntitySchemasTable) WithSuffix(suffix string) *EntitySchemasTable {
	return newEntitySchemasTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEntitySchemasTable(schemaName, tableName, alias string) *EntitySchemasTable {
	return &EntitySchemasTable{
		entitySchemasTable: newEntitySchemasTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newEntitySchemasTableImpl("", "excluded", ""),
	}
}

func newEntitySchemasTableImpl(schemaName, tableName, alias string) entitySchemasTable {
	var (
		IDColumn            = postgres.IntegerColumn("id")
		TenantIDColumn      = postgres.StringColumn("tenant_id")
		SchemaKeyColumn     = postgres.StringColumn("schema_key")
		SchemaName_Column   = postgres.StringColumn("schema_name")
		SchemaVersionColumn = postgres.StringColumn("schema_version")
		DescriptionColumn   = postgres.StringColumn("description")
		IsLatestColumn      = postgres.BoolColumn("is_latest")
		LifecycleColumn     = postgres.StringColumn("lifecycle")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampzColumn("updated_at")
		allColumns          = postgres.ColumnList{IDColumn, TenantIDColumn, SchemaKeyColumn, SchemaName_Column, SchemaVersionColumn, DescriptionColumn, IsLatestColumn, LifecycleColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{TenantIDColumn, SchemaKeyColumn, SchemaName_Column, SchemaVersionColumn, DescriptionColumn, IsLatestColumn, LifecycleColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns      = postgres.ColumnList{IDColumn, IsLatestColumn, LifecycleColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return entitySchemasTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		TenantID:      TenantIDColumn,
		SchemaKey:     SchemaKeyColumn,
		SchemaName_:   SchemaName_Column,
		SchemaVersion: SchemaVersionColumn,
		Description:   DescriptionColumn,
		IsLatest:      IsLatestColumn,
		Lifecycle:     LifecycleColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
