//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var EntityParameters = newEntityParametersTable("public", "entity_parameters", "")

type entityParametersTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnInteger
	TenantID      postgres.ColumnString
	ParameterName postgres.ColumnString
	DataType      postgres.ColumnString
	Description   postgres.ColumnString
	CreatedAt     postgres.ColumnTimestamp
	UpdatedAt     postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type EntityParametersTable struct {
	entityParametersTable

	EXCLUDED entityParametersTable
}

// AS creates new EntityParametersTable with assigned alias
func (a EntityParametersTable) AS(alias string) *EntityParametersTable {
	return newEntityParametersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EntityParametersTable with assigned schema name
func (a EntityParametersTable) FromSchema(schemaName string) *EntityParametersTable {
	return newEntityParametersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EntityParametersTable with assigned table prefix
func (a EntityParametersTable) WithPrefix(prefix string) *EntityParametersTable {
	return newEntityParametersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EntityParametersTable with assigned table suffix
func (a EntityParametersTable) WithSuffix(suffix string) *EntityParametersTable {
	return newEntityParametersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEntityParametersTable(schemaName, tableName, alias string) *EntityParametersTable {
	return &EntityParametersTable{
		entityParametersTable: newEntityParametersTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newEntityParametersTableImpl("", "excluded", ""),
	}
}

func newEntityParametersTableImpl(schemaName, tableName, alias string) entityParametersTable {
	var (
		IDColumn            = postgres.IntegerColumn("id")
		TenantIDColumn      = postgres.StringColumn("tenant_id")
		ParameterNameColumn = postgres.StringColumn("parameter_name")
		DataTypeColumn      = postgres.StringColumn("data_type")
		DescriptionColumn   = postgres.StringColumn("description")
		CreatedAtColumn     = postgres.TimestampColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampColumn("updated_at")
		allColumns          = postgres.ColumnList{IDColumn, TenantIDColumn, ParameterNameColumn, DataTypeColumn, DescriptionColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{TenantIDColumn, ParameterNameColumn, DataTypeColumn, DescriptionColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return entityParametersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		TenantID:      TenantIDColumn,
		ParameterName: ParameterNameColumn,
		DataType:      DataTypeColumn,
		Description:   DescriptionColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
